[build]
  base    = "."
  publish = ".dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline'"
  for = "/serviceworker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
